
//Set path to SmartSlog KP Library
#include <smartslog.h>

#ifndef _GENERATED_ONTOLOGY
#define	_GENERATED_ONTOLOGY


#ifdef	__cplusplus
extern "C" {
#endif


#define INCLUDE_ALL_ONT_ENTITIES 1
#ifdef INCLUDE_ALL_ONT_ENTITIES

#define INCLUDE_PROPERTY_HASRESPONSEITEM 1
#define INCLUDE_PROPERTY_LINKEDWITHITEM 1
#define INCLUDE_PROPERTY_ANWEREDTO 1
#define INCLUDE_PROPERTY_DESCRIPTION 1
#define INCLUDE_PROPERTY_ITEMSCORE 1
#define INCLUDE_PROPERTY_SUBANSWER 1
#define INCLUDE_PROPERTY_SINGLEITEM 1
#define INCLUDE_PROPERTY_FIRSTQUESTION 1
#define INCLUDE_PROPERTY_HASFEEDBACK 1
#define INCLUDE_PROPERTY_LEFTBIPOLAR 1
#define INCLUDE_PROPERTY_HASQUESTION 1
#define INCLUDE_PROPERTY_CONTAINSFILE 1
#define INCLUDE_PROPERTY_RANGINGITEM 1
#define INCLUDE_PROPERTY_CODE 1
#define INCLUDE_PROPERTY_HASANSWER 1
#define INCLUDE_PROPERTY_DICHOTOMOUSITEM 1
#define INCLUDE_PROPERTY_HASRESPONSE 1
#define INCLUDE_PROPERTY_RIGHTBIPOLAR 1
#define INCLUDE_PROPERTY_MULTIPLEITEM 1
#define INCLUDE_PROPERTY_CONTAINSSUBRESPONSE 1
#define INCLUDE_PROPERTY_ITEMTEXT 1
#define INCLUDE_PROPERTY_RESPONDEDTO 1
#define INCLUDE_PROPERTY_NEXTQUESTION 1
#define INCLUDE_PROPERTY_CONTAINSTEXT 1
#define INCLUDE_CLASS_PHOTO 1
#define INCLUDE_CLASS_THING 1
#define INCLUDE_CLASS_CHOISE 1
#define INCLUDE_CLASS_AUDIO 1
#define INCLUDE_CLASS_RESPONSEFILE 1
#define INCLUDE_CLASS_LIKERTSCALE 1
#define INCLUDE_CLASS_RESPONSETEXT 1
#define INCLUDE_CLASS_CLOSEDANSWER 1
#define INCLUDE_CLASS_QUESTION 1
#define INCLUDE_CLASS_QUESTIONNAIRE 1
#define INCLUDE_CLASS_MULTIPLECHOISE 1
#define INCLUDE_CLASS_FILE 1
#define INCLUDE_CLASS_ANSWER 1
#define INCLUDE_CLASS_EMAIL 1
#define INCLUDE_CLASS_DOCUMENT 1
#define INCLUDE_CLASS_FEEDBACK 1
#define INCLUDE_CLASS_NOTHING 1
#define INCLUDE_CLASS_PERSON 1
#define INCLUDE_CLASS_VALIDATED 1
#define INCLUDE_CLASS_ITEM 1
#define INCLUDE_CLASS_SINGLECHOISE 1
#define INCLUDE_CLASS_OPENANSWER 1
#define INCLUDE_CLASS_VIDEO 1
#define INCLUDE_CLASS_BIPOLARQUESTION 1
#define INCLUDE_CLASS_RESPONSE 1
#define INCLUDE_CLASS_NUMBER 1
#define INCLUDE_CLASS_TEXT 1
#define INCLUDE_CLASS_RANGINGSCALE 1
#define INCLUDE_CLASS_RESPONSEITEM 1
#define INCLUDE_CLASS_CONTINUOUSSCALE 1
#define INCLUDE_CLASS_PHONE 1
#define INCLUDE_CLASS_DICHOTOMOUS 1
#define INCLUDE_CLASS_GUTTMANSCALE 1


#else

#define INCLUDE_PROPERTY_HASRESPONSEITEM 0
#define INCLUDE_PROPERTY_LINKEDWITHITEM 0
#define INCLUDE_PROPERTY_ANWEREDTO 0
#define INCLUDE_PROPERTY_DESCRIPTION 0
#define INCLUDE_PROPERTY_ITEMSCORE 0
#define INCLUDE_PROPERTY_SUBANSWER 0
#define INCLUDE_PROPERTY_SINGLEITEM 0
#define INCLUDE_PROPERTY_FIRSTQUESTION 0
#define INCLUDE_PROPERTY_HASFEEDBACK 0
#define INCLUDE_PROPERTY_LEFTBIPOLAR 0
#define INCLUDE_PROPERTY_HASQUESTION 0
#define INCLUDE_PROPERTY_CONTAINSFILE 0
#define INCLUDE_PROPERTY_RANGINGITEM 0
#define INCLUDE_PROPERTY_CODE 0
#define INCLUDE_PROPERTY_HASANSWER 0
#define INCLUDE_PROPERTY_DICHOTOMOUSITEM 0
#define INCLUDE_PROPERTY_HASRESPONSE 0
#define INCLUDE_PROPERTY_RIGHTBIPOLAR 0
#define INCLUDE_PROPERTY_MULTIPLEITEM 0
#define INCLUDE_PROPERTY_CONTAINSSUBRESPONSE 0
#define INCLUDE_PROPERTY_ITEMTEXT 0
#define INCLUDE_PROPERTY_RESPONDEDTO 0
#define INCLUDE_PROPERTY_NEXTQUESTION 0
#define INCLUDE_PROPERTY_CONTAINSTEXT 0
#define INCLUDE_CLASS_PHOTO 0
#define INCLUDE_CLASS_THING 0
#define INCLUDE_CLASS_CHOISE 0
#define INCLUDE_CLASS_AUDIO 0
#define INCLUDE_CLASS_RESPONSEFILE 0
#define INCLUDE_CLASS_LIKERTSCALE 0
#define INCLUDE_CLASS_RESPONSETEXT 0
#define INCLUDE_CLASS_CLOSEDANSWER 0
#define INCLUDE_CLASS_QUESTION 0
#define INCLUDE_CLASS_QUESTIONNAIRE 0
#define INCLUDE_CLASS_MULTIPLECHOISE 0
#define INCLUDE_CLASS_FILE 0
#define INCLUDE_CLASS_ANSWER 0
#define INCLUDE_CLASS_EMAIL 0
#define INCLUDE_CLASS_DOCUMENT 0
#define INCLUDE_CLASS_FEEDBACK 0
#define INCLUDE_CLASS_NOTHING 0
#define INCLUDE_CLASS_PERSON 0
#define INCLUDE_CLASS_VALIDATED 0
#define INCLUDE_CLASS_ITEM 0
#define INCLUDE_CLASS_SINGLECHOISE 0
#define INCLUDE_CLASS_OPENANSWER 0
#define INCLUDE_CLASS_VIDEO 0
#define INCLUDE_CLASS_BIPOLARQUESTION 0
#define INCLUDE_CLASS_RESPONSE 0
#define INCLUDE_CLASS_NUMBER 0
#define INCLUDE_CLASS_TEXT 0
#define INCLUDE_CLASS_RANGINGSCALE 0
#define INCLUDE_CLASS_RESPONSEITEM 0
#define INCLUDE_CLASS_CONTINUOUSSCALE 0
#define INCLUDE_CLASS_PHONE 0
#define INCLUDE_CLASS_DICHOTOMOUS 0
#define INCLUDE_CLASS_GUTTMANSCALE 0


#endif


#if INCLUDE_CLASS_PHOTO
extern sslog_class_t *CLASS_PHOTO;
#endif
#if INCLUDE_CLASS_THING
extern sslog_class_t *CLASS_THING;
#endif
#if INCLUDE_CLASS_CHOISE
extern sslog_class_t *CLASS_CHOISE;
#endif
#if INCLUDE_CLASS_AUDIO
extern sslog_class_t *CLASS_AUDIO;
#endif
#if INCLUDE_CLASS_RESPONSEFILE
extern sslog_class_t *CLASS_RESPONSEFILE;
#endif
#if INCLUDE_CLASS_LIKERTSCALE
extern sslog_class_t *CLASS_LIKERTSCALE;
#endif
#if INCLUDE_CLASS_RESPONSETEXT
extern sslog_class_t *CLASS_RESPONSETEXT;
#endif
#if INCLUDE_CLASS_CLOSEDANSWER
extern sslog_class_t *CLASS_CLOSEDANSWER;
#endif
#if INCLUDE_CLASS_QUESTION
extern sslog_class_t *CLASS_QUESTION;
#endif
#if INCLUDE_CLASS_QUESTIONNAIRE
extern sslog_class_t *CLASS_QUESTIONNAIRE;
#endif
#if INCLUDE_CLASS_MULTIPLECHOISE
extern sslog_class_t *CLASS_MULTIPLECHOISE;
#endif
#if INCLUDE_CLASS_FILE
extern sslog_class_t *CLASS_FILE;
#endif
#if INCLUDE_CLASS_ANSWER
extern sslog_class_t *CLASS_ANSWER;
#endif
#if INCLUDE_CLASS_EMAIL
extern sslog_class_t *CLASS_EMAIL;
#endif
#if INCLUDE_CLASS_DOCUMENT
extern sslog_class_t *CLASS_DOCUMENT;
#endif
#if INCLUDE_CLASS_FEEDBACK
extern sslog_class_t *CLASS_FEEDBACK;
#endif
#if INCLUDE_CLASS_NOTHING
extern sslog_class_t *CLASS_NOTHING;
#endif
#if INCLUDE_CLASS_PERSON
extern sslog_class_t *CLASS_PERSON;
#endif
#if INCLUDE_CLASS_VALIDATED
extern sslog_class_t *CLASS_VALIDATED;
#endif
#if INCLUDE_CLASS_ITEM
extern sslog_class_t *CLASS_ITEM;
#endif
#if INCLUDE_CLASS_SINGLECHOISE
extern sslog_class_t *CLASS_SINGLECHOISE;
#endif
#if INCLUDE_CLASS_OPENANSWER
extern sslog_class_t *CLASS_OPENANSWER;
#endif
#if INCLUDE_CLASS_VIDEO
extern sslog_class_t *CLASS_VIDEO;
#endif
#if INCLUDE_CLASS_BIPOLARQUESTION
extern sslog_class_t *CLASS_BIPOLARQUESTION;
#endif
#if INCLUDE_CLASS_RESPONSE
extern sslog_class_t *CLASS_RESPONSE;
#endif
#if INCLUDE_CLASS_NUMBER
extern sslog_class_t *CLASS_NUMBER;
#endif
#if INCLUDE_CLASS_TEXT
extern sslog_class_t *CLASS_TEXT;
#endif
#if INCLUDE_CLASS_RANGINGSCALE
extern sslog_class_t *CLASS_RANGINGSCALE;
#endif
#if INCLUDE_CLASS_RESPONSEITEM
extern sslog_class_t *CLASS_RESPONSEITEM;
#endif
#if INCLUDE_CLASS_CONTINUOUSSCALE
extern sslog_class_t *CLASS_CONTINUOUSSCALE;
#endif
#if INCLUDE_CLASS_PHONE
extern sslog_class_t *CLASS_PHONE;
#endif
#if INCLUDE_CLASS_DICHOTOMOUS
extern sslog_class_t *CLASS_DICHOTOMOUS;
#endif
#if INCLUDE_CLASS_GUTTMANSCALE
extern sslog_class_t *CLASS_GUTTMANSCALE;
#endif


#if INCLUDE_PROPERTY_HASRESPONSEITEM
extern sslog_property_t *PROPERTY_HASRESPONSEITEM;
#endif
#if INCLUDE_PROPERTY_LINKEDWITHITEM
extern sslog_property_t *PROPERTY_LINKEDWITHITEM;
#endif
#if INCLUDE_PROPERTY_ANWEREDTO
extern sslog_property_t *PROPERTY_ANWEREDTO;
#endif
#if INCLUDE_PROPERTY_DESCRIPTION
extern sslog_property_t *PROPERTY_DESCRIPTION;
#endif
#if INCLUDE_PROPERTY_ITEMSCORE
extern sslog_property_t *PROPERTY_ITEMSCORE;
#endif
#if INCLUDE_PROPERTY_SUBANSWER
extern sslog_property_t *PROPERTY_SUBANSWER;
#endif
#if INCLUDE_PROPERTY_SINGLEITEM
extern sslog_property_t *PROPERTY_SINGLEITEM;
#endif
#if INCLUDE_PROPERTY_FIRSTQUESTION
extern sslog_property_t *PROPERTY_FIRSTQUESTION;
#endif
#if INCLUDE_PROPERTY_HASFEEDBACK
extern sslog_property_t *PROPERTY_HASFEEDBACK;
#endif
#if INCLUDE_PROPERTY_LEFTBIPOLAR
extern sslog_property_t *PROPERTY_LEFTBIPOLAR;
#endif
#if INCLUDE_PROPERTY_HASQUESTION
extern sslog_property_t *PROPERTY_HASQUESTION;
#endif
#if INCLUDE_PROPERTY_CONTAINSFILE
extern sslog_property_t *PROPERTY_CONTAINSFILE;
#endif
#if INCLUDE_PROPERTY_RANGINGITEM
extern sslog_property_t *PROPERTY_RANGINGITEM;
#endif
#if INCLUDE_PROPERTY_CODE
extern sslog_property_t *PROPERTY_CODE;
#endif
#if INCLUDE_PROPERTY_HASANSWER
extern sslog_property_t *PROPERTY_HASANSWER;
#endif
#if INCLUDE_PROPERTY_DICHOTOMOUSITEM
extern sslog_property_t *PROPERTY_DICHOTOMOUSITEM;
#endif
#if INCLUDE_PROPERTY_HASRESPONSE
extern sslog_property_t *PROPERTY_HASRESPONSE;
#endif
#if INCLUDE_PROPERTY_RIGHTBIPOLAR
extern sslog_property_t *PROPERTY_RIGHTBIPOLAR;
#endif
#if INCLUDE_PROPERTY_MULTIPLEITEM
extern sslog_property_t *PROPERTY_MULTIPLEITEM;
#endif
#if INCLUDE_PROPERTY_CONTAINSSUBRESPONSE
extern sslog_property_t *PROPERTY_CONTAINSSUBRESPONSE;
#endif
#if INCLUDE_PROPERTY_ITEMTEXT
extern sslog_property_t *PROPERTY_ITEMTEXT;
#endif
#if INCLUDE_PROPERTY_RESPONDEDTO
extern sslog_property_t *PROPERTY_RESPONDEDTO;
#endif
#if INCLUDE_PROPERTY_NEXTQUESTION
extern sslog_property_t *PROPERTY_NEXTQUESTION;
#endif
#if INCLUDE_PROPERTY_CONTAINSTEXT
extern sslog_property_t *PROPERTY_CONTAINSTEXT;
#endif



void register_ontology();

	
#ifdef	__cplusplus
}
#endif

#endif /* _GENERATED_ONTOLOGY */
